src/AresliaBundle/Entity/Promotion.php
<?php

namespace AresliaBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Promotion
 *
 * @ORM\Table(name="promotion", indexes={@ORM\Index(name="fk", columns={"id_categorie_promo"})})
 * @ORM\Entity
 */
class Promotion
{
    /**
     * @var string
     *
     * @ORM\Column(name="titre", type="string", length=255, nullable=false)
     */
    private $titre;

    /**
     * @var string
     *
     * @ORM\Column(name="Descreption", type="string", length=255, nullable=false)
     */
    private $descreption;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="Date_Validite", type="date", nullable=true)
     */
    private $dateValidite;

    /**
     * @var float
     *
     * @ORM\Column(name="Pourcentage", type="float", precision=10, scale=0, nullable=false)
     */
    private $pourcentage;

    /**
     * @var string
     *
     * @ORM\Column(name="Image", type="string", length=500, nullable=false)
     */
    private $image;

    /**
     * @var integer
     *
     * @ORM\Column(name="Prix", type="integer", nullable=false)
     */
    private $prix;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date_ajout", type="date", nullable=false)
     */
    private $dateAjout;

    /**
     * @var integer
     *
     * @ORM\Column(name="id_Promotion", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $idPromotion;

    /**
     * @var \AresliaBundle\Entity\CatergoriePromo
     *
     * @ORM\ManyToOne(targetEntity="AresliaBundle\Entity\CatergoriePromo")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_categorie_promo", referencedColumnName="idCategrie")
     * })
     */
    private $idCategoriePromo;


    /**
     * @Assert\File(
     *     maxSize = "500M",
     *
     *     uploadIniSizeErrorMessage = "uploaded file is larger than the upload_max_filesize PHP.ini setting",
     *     uploadFormSizeErrorMessage = "uploaded file is larger than allowed by the HTML file input field",
     *     uploadErrorMessage = "uploaded file could not be uploaded for some unknown reason",
     *     maxSizeMessage = "fichier trop volumineux"
     * )
     */
    public $file;










    function setImage($image) {
        $this->image =$image;
    }


    public function getAbsolutePath() {
        return null === $this->image ? null : $this->getUploadRootDir() . '/' . $this->image;
    }

    public function getWebPath() {
        return null === $this->image ? null : $this->getUploadDir() . '/' . $this->image;
    }

    protected function getUploadRootDir() {
        // the absolute directory path where uploaded
        // documents should be saved
        return __DIR__ . '/../../../web/upload/' . $this->getUploadDir();
    }

    protected function getUploadDir() {
        // get rid of the __DIR__ so it doesn't screw up
        // when displaying uploaded doc/image in the view.
        return '/Promotion/';
    }

    /**
     * Sets file.
     *
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file = null) {
        $this->file = $file;
    }

    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getFile() {
        return $this->file;
    }

    public function upload() {
        // the file property can be empty if the field is not required
        if (null === $this->getFile()) {
            return;
        }
$date = new \DateTime();
        $timestamp = $date->format('U');
        // use the original file name here but you should
        // sanitize it at least to avoid any security issues
        // move takes the target directory and then the
        // target filename to move to

//$filename = "" . $timestamp . basename($file->getClientOriginalName());
        $this->file->move($this->getUploadRootDir(), "" . $timestamp . basename($this->titre));

        // On sauvegarde le nom de fichier
        $this->image = "" . $timestamp . basename($this->titre);


        // La propriété file ne servira plus
        $this->file = null;
    }


    /**
     * @return string
     */
    public function getTitre()
    {
        return $this->titre;
    }

    /**
     * @param string $titre
     */
    public function setTitre($titre)
    {
        $this->titre = $titre;
    }

    /**
     * @return string
     */
    public function getDescreption()
    {
        return $this->descreption;
    }

    /**
     * @param string $descreption
     */
    public function setDescreption($descreption)
    {
        $this->descreption = $descreption;
    }

    /**
     * @return \DateTime
     */
    public function getDateValidite()
    {
        return $this->dateValidite;
    }

    /**
     * @param \DateTime $dateValidite
     */
    public function setDateValidite($dateValidite)
    {
        $this->dateValidite = $dateValidite;
    }

    /**
     * @return float
     */
    public function getPourcentage()
    {
        return $this->pourcentage;
    }

    /**
     * @param float $pourcentage
     */
    public function setPourcentage($pourcentage)
    {
        $this->pourcentage = $pourcentage;
    }



    /**
     * @return int
     */
    public function getPrix()
    {
        return $this->prix;
    }

    /**
     * @param int $prix
     */
    public function setPrix($prix)
    {
        $this->prix = $prix;
    }

    /**
     * @return \DateTime
     */
    public function getDateAjout()
    {
        return $this->dateAjout;
    }

    /**
     * @param \DateTime $dateAjout
     */
    public function setDateAjout($dateAjout)
    {
        $this->dateAjout = $dateAjout;
    }

    /**
     * @return int
     */
    public function getIdPromotion()
    {
        return $this->idPromotion;
    }

    /**
     * @param int $idPromotion
     */
    public function setIdPromotion($idPromotion)
    {
        $this->idPromotion = $idPromotion;
    }

    /**
     * @return CatergoriePromo
     */
    public function getIdCategoriePromo()
    {
        return $this->idCategoriePromo;
    }

    /**
     * @param CatergoriePromo $idCategoriePromo
     */
    public function setIdCategoriePromo($idCategoriePromo)
    {
        $this->idCategoriePromo = $idCategoriePromo;
    }

    /**
     * @return string
     */
    public function getImage()
    {
        return $this->image;
    }


}

src/AresliaBundle/Resources/views/Promtion/AddPromotion.html.twig
{% extends 'AresliaBundle:Default:index.html.twig' %}
  {% block body %}

      <div id="page-content-wrapper">
          <div id="page-content">

              <div class="container">


                  <!-- Parsley -->

                  <script type="text/javascript" src="{{asset('assets/widgets/parsley/parsley.js')}}"></script>

                  <div id="page-title">
                      <h2>Ajouter Promotion</h2>


                  </div>

                  <div class="panel">
                      <div class="panel-body">

                          <div class="example-box-wrapper">
                              <form  method="post" action="{{ path('areslia_AddPromotion') }}" class="form-horizontal bordered-row" id="demo-form" data-parsley-validate="" enctype="multipart/form-data" novalidate="">
                                  <div class="row">
                                      <div class="col-md-6">
                                          <div class="form-group">
                                              <label class="col-sm-3 control-label">Titre Promotion</label>
                                              <div class="col-sm-6">
                                                  <input type="text" placeholder="Titre Promotion" required=""  name="titre" class="form-control" data-parsley-id="8799"><ul class="parsley-errors-list" id="parsley-id-8799"></ul>
                                              </div>
                                          </div>
                                          <div class="form-group">
                                              <label class="col-sm-3 control-label">Categorie</label>
                                              <div class="col-sm-6">
                                                  <input type="text" placeholder="Categorie" required="" list="mylist" name="categorie" class="form-control awesomplete" >
                                                  <datalist id="mylist">
      {% for categorie in categories %}
                                                      <option>{{ categorie.categrie }}</option>

      {% endfor %}
                                                  </datalist>
                                              </div>
                                          </div>
                                          <div class="form-group">
                                              <label class="col-sm-3 control-label">Description</label>
                                              <div class="col-sm-6">
                                                  <textarea maxlength="225" id="" style="height: 150px;width: 350px;" name="descreption" placeholder="Description" required="" class="form-control"></textarea>
                                              </div>
                                          </div>


                                          <div class="form-group">
                                              <label for="" class="col-sm-3 control-label">Date Validité</label>
                                              <div class="col-sm-8">
                                                  <div class="input-prepend input-group">
                                    <span class="add-on input-group-addon">
                                        <i class="glyph-icon icon-calendar"></i>
                                    </span>
                                                      <input type="date" name="date" class="bootstrap-datepicker form-control" value="02/16/12" required="" data-date-format="mm/dd/yy">
                                                  </div>
                                              </div>
                                          </div>

                                          <div class="form-group">
                                              <label class="col-sm-3 control-label">Prix</label>
                                              <div class="col-sm-6">
                                                  <input id="touchspin-demo-1" required="" placeholder="Prix" name="prix" class="form-control" type="number"  >
                                              </div>
                                          </div>

                                          <div class="form-group">
                                              <label class="col-sm-3 control-label">Pourcentage Reduction</label>
                                              <div class="col-sm-6">
                                                  <input id="touchspin-demo-1" name="reduction" placeholder="Pourcentage Reduction" required="" class="form-control" type="number" >
                                              </div>
                                          </div>




                                      </div>
                                      <div class="form-group">
                                          <label class="col-sm-3 control-label"></label>
                                          <div class="col-sm-6">
                                              <div class="fileinput fileinput-new" data-provides="fileinput">
                                                  <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;">

                                                      <img src="" id="blah">
                                                  </div>
                                                  <div>
                                <span class="btn btn-default btn-file">
                                    <span class="fileinput-new">Select image</span>
                                    <span class="fileinput-exists">Change</span>
                                    <input type="file" required="" id="fileinput" name="file">
                                </span>
                                                      <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                  </div>

                                  <div class="bg-default content-box text-center pad20A mrg25T">
                                      <button class="btn btn-lg btn-primary">Ajouter</button>
                                  </div>
                              </form>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
<script>


    function readURL(input) {

        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#blah').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#fileinput").change(function(){
        readURL(this);
    });
</script>


      </div> {% endblock %}

src/AresliaBundle/Resources/views/Promtion/ListPromotion.html.twig
{% extends 'AresliaBundle:Default:index.html.twig' %}
  {% block body %}

      <div id="page-content-wrapper">
          <div id="page-content">

              <div class="container" style="background-color: transparent">


                  <div id="page-title">
                      <h2>Nos Promotions</h2>

                      <a style="float:right;bottom: -32px;    background-color: #62bddc;"href="{{path('areslia_AddPromo')}}" class="btn btn-alt btn-hover ">
                          <span style="color: black;">Ajouter Promotion</span>
                          <i class="glyph-icon icon-plus"></i>
                      </a>
                      <p></p>

                  </div>
                  <link rel="stylesheet" type="text/css" href="{{asset('assets/frontend-elements/blog.css')}}">

                  <!-- Owlcarousel -->
                  <link rel="stylesheet" type="text/css" href="{{asset('assets/widgets/owlcarousel/owlcarousel.css')}}">
                  <script type="text/javascript" src="{{asset('assets/widgets/owlcarousel/owlcarousel.js')}}"></script>
                  <script type="text/javascript" src="{{asset('assets/widgets/owlcarousel/owlcarousel-demo.js')}}"></script>

                  <!-- Lazyload -->

                  <script type="text/javascript" src="{{asset('assets/widgets/lazyload/lazyload.js')}}"></script>
                  <script type="text/javascript">
                      /* Lazyload */

                      $(function() {
                          $("img.lazy").lazyload({
                              effect: "fadeIn",
                              threshold: 100
                          });
                      });
                  </script>

                  <!-- PrettyPhoto modals -->

                  <link rel="stylesheet" type="text/css" href="{{asset('assets/widgets/pretty-photo/prettyphoto.css')}}">
                  <script type="text/javascript" src="{{asset('assets/widgets/pretty-photo/prettyphoto.js')}}"></script>
                  <script type="text/javascript">
                      /* PrettyPhoto */

                      $(document).ready(function() {
                          $(".prettyphoto").prettyPhoto();
                      });
                  </script>

                  <div  class="row ">

                      <input style="margin: 10px;width: 800px"  type="text" id="myInput" onkeyup="myFunction()" placeholder="Recherche.." required="" class="form-control" data-parsley-id="8799"><ul class="parsley-errors-list" id="parsley-id-8799"></ul>

                      <div class="col-md-3" style="float:right;padding: 10px;">

                          <div class="content-box">
                              <h3 class="content-box-header bg-default">
                                  Notifications récentes
                              </h3>
                              <div class="posts-list content-box-wrapper">
                                  <ul id="UL" class="">
                                      {% for Notification in Notifications|reverse[:3] %}
                                          <li name="li">
                                              <div class="post-image">
                                                  <a href="{{asset('assets/image-resources/stock-images/img-10.jpg')}}" class="prettyphoto" rel="prettyPhoto[pp_gal]" title="Blog post title">
                                                      <img  class="img-responsive" src="http://app.arislia.fr/upload/{{  Notification.idPromo.webPath }}" alt="">
                                                  </a>
                                              </div>
                                              <div class="post-body">
                                                  <a class="post-title" href="#" title="">
                                                      <h3 >{{  Notification.idPromo.titre }}</h3>
                                                  </a>
                                                  <p  >{{  Notification.message }}</p>
                                              </div>
                                          </li>
                                      {% endfor %}

                                  </ul>
                              </div>
                          </div>




                      </div>
                      <div id="paging_container4" >
                          <div id="page_navigation_top" class="page_navigation" style=""></div>
                      <ul id="myUL" class="col-md-9 content">

                          {% for Promotio in Promotion|reverse %}
                          <li id="P{{ Promotio.idPromotion }}" class="blog-box row">
                              <div class="post-image col-md-4">

                                      <img class="img-responsive lazy img-rounded" src="http://app.arislia.fr/upload/{{ Promotio.webPath }}" id="I{{ Promotio.idPromotion }}" data-original="http://app.arislia.fr/upload/{{ Promotio.webPath }}" alt="">

                              </div>
                              <div class="post-content-wrapper col-md-8">
                                  <a class="post-title" href="#" title="">
                                      <h3 id="t{{ Promotio.idPromotion }}">{{ Promotio.titre }}</h3>
                                  </a>
                                  <div class="post-meta">
                    <span>
                        <i class="glyph-icon icon-clock-o"></i>
                       <span> {{ Promotio.dateValidite|date('d/m/y')}}</span>
                    </span>

                                  </div>
                                  <div class="post-content">
                                      <p id="D{{ Promotio.idPromotion }}">{{ Promotio.descreption }}</p>
                                  </div>
                                  <a  onclick="notif({{ Promotio.idPromotion }})"  class="btn btn-sm btn-default" style="background-color: #62bddc;" title="Envoyer une Notification">Envoyer Notifications</a>
                                  <a  href="{{ path('areslia_modifredirect',{'id': Promotio.idPromotion }) }}" class="btn btn-sm btn-default" style="background-color: #62bddc;"  title="Modifier">Modifier</a>
                                  <a onclick="supp({{ Promotio.idPromotion }})"  class="btn btn-md btn-danger delete"   title="Modifier">Supprimer</a>

                              </div>
                          </li>
{% endfor %}


                      </ul>

                          <div class="page_navigation " style=""></div>

                      </div>


                  </div>

              </div>



          </div>
      </div>


      <script>


          // var alertt = document.getElementById("alert");
          function supp(x){
              var retVal = confirm("Êtes-vous absolument certain de vouloir supprimer?");
              if(retVal==true){
                  $.get("http://app.arislia.fr/suppromotion/"+x, function(data, status){
                      console.log("ssss"+data);



                  });
                  document.getElementById("P"+x).remove();
              }}

      </script>
      <script>
          $(document).ready(function(){
              $('#paging_container4').pajinate({
                  items_per_page : 3,
                  nav_label_first : '<<',
                  nav_label_last : '>>',
                  nav_label_prev : '<',
                  nav_label_next : '>'


              });
          });</script>
      <script>


          // var alertt = document.getElementById("alert");
          function notif(x){
              var I= document.getElementById("I"+x).src;
              var t= document.getElementById("t"+x).innerHTML;
              var D= document.getElementById("D"+x).innerHTML;
              $.get("http://app.arislia.fr/sendnotification/"+x, function(data, status){
                  console.log("ssss"+data);



              });
              alert("Envoie effectué avec succes.");


              //   document.getElementById("UL").append('<li>aaaaaaaa</li>');
              var x = document.createElement("IMG");
              var createA = document.createElement('a');
              var div1 = document.createElement('DIV');
              var div2 = document.createElement('DIV');
              var  tt= document.createElement('h3');
              var  p= document.createElement('P');
              var text = document.createTextNode(t);
              var DD = document.createTextNode(D);



              var createA2 = document.createElement('a');
              x.setAttribute("src", I);
              createA.setAttribute("class",'prettyphoto');
              createA2.setAttribute("class",'post-title');
              x.setAttribute("class", "img-responsive");
              x.setAttribute("alt", "The Pulpit Rock");
              div1.setAttribute("class", "post-image");
              div2.setAttribute("class", "post-body");
              createA.append(x);
              div1.append(createA);
              tt.append(t);
              createA2.append(tt);
              p.append(D);
              div2.append(createA2);
              div2.append(p);
              var newLi = document.createElement("li");
              newLi.setAttribute("name",'li');

              newLi.append( div1 );
              newLi.append( div2 );

              document.getElementById("UL").prepend(newLi);
              document.getElementsByName("li")[3].remove();

          }
      </script>




  {% endblock %}

src/AresliaBundle/Resources/views/Promtion/ModifPromotion.html.twig
{% extends 'AresliaBundle:Default:index.html.twig' %}
  {% block body %}

      <div id="page-content-wrapper">
          <div id="page-content">

              <div class="container">


                  <!-- Parsley -->

                  <script type="text/javascript" src="{{asset('assets/widgets/parsley/parsley.js')}}"></script>

                  <div id="page-title">
                      <h2>Modifier Promotion</h2>


                  </div>

                  <div class="panel">
                      <div class="panel-body">

                          <div class="example-box-wrapper">
                              <form  method="post" action="{{ path('areslia_modifpromo',{'id': Promotion.id_Promotion }) }}" class="form-horizontal bordered-row" id="demo-form" data-parsley-validate="" enctype="multipart/form-data" novalidate="">
                                  <div class="row">
                                      <div class="col-md-6">
                                          <div class="form-group">
                                              <label class="col-sm-3 control-label">Titre Promotion</label>
                                              <div class="col-sm-6">
                                                  <input type="text" value="{{ Promotion.titre }}" placeholder="" required=""  name="titre" class="form-control" data-parsley-id="8799"><ul class="parsley-errors-list" id="parsley-id-8799"></ul>

                                              </div>

                                          </div>
                                          <div class="form-group">
                                              <label class="col-sm-3 control-label">Categorie</label>
                                              <div class="col-sm-6">
                                                  <input type="text" placeholder="" required="" value="{{ Promotion.categrie }}" list="mylist" name="categorie" class="form-control awesomplete" >
                                                  <datalist id="mylist">
                                                      {% for categorie in categories %}
                                                          <option>{{ categorie.categrie }}</option>

                                                      {% endfor %}
                                                  </datalist>
                                              </div>
                                          </div>
                                          <div class="form-group">
                                              <label class="col-sm-3 control-label">Descreption</label>
                                              <div class="col-sm-6">
                                                  <textarea maxlength="225" style="height: 150px;width: 350px;"  name="descreption"  required="" class="form-control">{{  Promotion.Descreption }}</textarea>

                                              </div>
                                          </div>


                                          <div class="form-group">
                                              <label for="" class="col-sm-3 control-label">Date Validité</label>
                                              <div class="col-sm-8">
                                                  <div class="input-prepend input-group">
                                    <span class="add-on input-group-addon">
                                        <i class="glyph-icon icon-calendar"></i>
                                    </span>

                                                      <input type="date" name="date" class="bootstrap-datepicker form-control" value="{{ Promotion.Date_Validite }}" required="" data-date-format="d/m/y">
                                                  </div>
                                              </div>
                                          </div>

                                          <div class="form-group">
                                              <label class="col-sm-3 control-label">Prix</label>
                                              <div class="col-sm-6">
                                                  <input id="touchspin-demo-1" required="" name="prix" class="form-control" type="text" value="{{ Promotion.Prix }}" name="touchspin-demo-1">
                                              </div>
                                          </div>

                                          <div class="form-group">
                                              <label class="col-sm-3 control-label">Pourcentage Reduction</label>
                                              <div class="col-sm-6">
                                                  <input id="touchspin-demo-1" name="reduction" required="" class="form-control" type="text" value="{{ Promotion.Pourcentage }}" name="touchspin-demo-1">
                                              </div>
                                          </div>




                                      </div>
                                      <div class="form-group">
                                          <label class="col-sm-3 control-label"></label>
                                          <div class="col-sm-6">
                                              <div class="fileinput fileinput-new" data-provides="fileinput">
                                                  <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;">
                                                      <img id="blah"  src="http://app.arislia.fr/upload/Promotion/{{ Promotion.Image }}" data-original="" alt=""></div>
                                                  <div>
                                <span class="btn btn-default btn-file">
                                    <span class="fileinput-new">Select image</span>
                                    <span class="fileinput-exists">Change</span>
                                    <input type="file" id="fileinput" name="file">
                                </span>
                                                      <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                  </div>

                                  <div class=" content-box text-center pad20A mrg25T">
                                      <button class="btn btn-lg btn-primary">Modifier</button>
                                  </div>
                              </form>
                          </div>
                      </div>
                  </div>
              </div>
          </div>

          <script>


              function readURL(input) {

                  if (input.files && input.files[0]) {
                      var reader = new FileReader();

                      reader.onload = function (e) {
                          $('#blah').attr('src', e.target.result);
                      }

                      reader.readAsDataURL(input.files[0]);
                  }
              }

              $("#fileinput").change(function(){
                  readURL(this);
              });
          </script>

      </div> {% endblock %}